{
  "openapi": "3.0.1",
  "info": {
    "title": "Global Markets \u2013 Munibonds Saved Search Updates",
    "description": "Allows a user to create saved searches to notify them of bonds that interest them.",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0",
    "x-additionalDocs": {
      "overview": {
        "fileName": ""
      }
    }
  },
  "tags": [
    {
      "name": "Muni Services"
    }
  ],
  "paths": {
    "/muni/v1/munibonds/savedsearch/update": {
      "post": {
        "tags": [
          "Muni Services"
        ],
        "summary": "APIs that allow BofA Securities customers of Municipal Banking and Markets to transact Municipal securities and create saved searches to notify them of bonds that interest them. This is canonical with the Offer API that is used to search for BofA Securities inventory. This API allows the user to register that search for notifications of new bonds that fit the criteria provided",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "Identify the content of the payload as JSON. Use 'Content-Type: application/json'. This is the only content type supported as of now. Content-Types cannot be negotiated programmatically at this time. Future versions might provide that facility",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "A unique access token to be used for a single request (ex. \u201cBearer [value])",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "userId",
            "in": "header",
            "description": "User who is interacting with this service from a company. User should be on boarded on the Bofa Securities Mercury\u2122 platform and obtain userId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "clientRequestId",
            "in": "header",
            "description": "A token provided by client to identify their request",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "Saved Search Update Request Body",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/requestBody"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/response"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/400ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Authentication Failure",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/401ErrorResponse"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/403ErrorResponse"
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/404ErrorResponse"
                }
              }
            }
          },
          "405": {
            "description": "Method Not Allowed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/405ErrorResponse"
                }
              }
            }
          },
          "406": {
            "description": "Not Acceptable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/406ErrorResponse"
                }
              }
            }
          },
          "408": {
            "description": "HTTP Timeout Exception",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/408ErrorResponse"
                }
              }
            }
          },
          "415": {
            "description": "Unsupported Media Type",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/415ErrorResponse"
                }
              }
            }
          },
          "429": {
            "description": "API calls exceeded",
            "content": {}
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/500ErrorResponse"
                }
              }
            }
          },
          "503": {
            "description": "Service unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/503ErrorResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "requestBody": {
        "type": "object",
        "required": [
          "addSavedSearch",
          "updateSavedSearch",
          "deleteSavedSearch"
        ],
        "properties": {
          "addSavedSearch": {
            "type": "array",
            "description": "Array of saved search to be added",
            "items": {
              "$ref": "#/components/schemas/AddSavedSearch"
            }
          },
          "updateSavedSearch": {
            "type": "array",
            "description": "Array of saved searches to be updated",
            "items": {
              "$ref": "#/components/schemas/UpdateSavedSearch"
            }
          },
          "deleteSavedSearch": {
            "type": "array",
            "description": "String Array of saved searches to be deleted",
            "items": {
              "type": "string"
            }
          }
        },
        "example": {
          "addSavedSearch": [
            {
              "criteria": [
                {
                  "field": "coupon",
                  "operand": "<=",
                  "value": "2"
                }
              ],
              "name": "Coupon1",
              "notification": "true"
            }
          ],
          "updateSavedSearch": [
            {
              "criteria": [
                {
                  "field": "coupon",
                  "operand": "<=",
                  "value": "1"
                }
              ],
              "name": "1cpn",
              "notification": "true"
            }
          ],
          "deleteSavedSearch": [
            "5cpn"
          ]
        }
      },
      "AddSavedSearch": {
        "type": "object",
        "properties": {
          "criteria": {
            "type": "array",
            "description": "Criteria of saved search",
            "items": {
              "$ref": "#/components/schemas/CriteriaAddArray"
            }
          },
          "name": {
            "type": "string",
            "description": "Name of saved search",
            "example": "Coupon1"
          },
          "notification": {
            "type": "boolean",
            "description": "Set true if user needs any offer updates notification matching with saved search criteria. The Email address on file with BofA Securities Mercury\u2122 will receive an email when inventory matches this saved search",
            "example": true
          }
        }
      },
      "CriteriaAddArray": {
        "type": "object",
        "properties": {
          "field": {
            "type": "string",
            "description": "Field represent different offer criteria properties.\nRefer to Offer API for fields",
            "example": "coupon"
          },
          "operand": {
            "type": "string",
            "description": "Valid operand corresponding to field",
            "example": "<="
          },
          "value": {
            "type": "string",
            "description": "Value set for criteria field",
            "example": "2"
          }
        }
      },
      "UpdateSavedSearch": {
        "type": "object",
        "properties": {
          "criteria": {
            "type": "array",
            "description": "Criteria of saved search",
            "items": {
              "$ref": "#/components/schemas/CriteriaUpdateArray"
            }
          },
          "name": {
            "type": "string",
            "description": "Name of saved search",
            "example": "1cpn"
          },
          "notification": {
            "type": "boolean",
            "description": "Set true if user needs any offer updates notification matching with saved search criteria. The Email address on file with BofA Securities Mercury\u2122 will receive an email when inventory matches this saved search",
            "example": true
          }
        }
      },
      "CriteriaUpdateArray": {
        "type": "object",
        "properties": {
          "field": {
            "type": "string",
            "description": "Field represent different offer criteria properties.\nRefer to Offer API for fields",
            "example": "coupon"
          },
          "operand": {
            "type": "string",
            "description": "Valid operand corresponding to field",
            "example": "<="
          },
          "value": {
            "type": "string",
            "description": "Value set for criteria field",
            "example": "1"
          }
        }
      },
      "response": {
        "type": "object"
      },
      "400ErrorResponse": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/400Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "clientRequestId:123",
          "status": "Failure",
          "apiName": "muni/v1/munibonds/savedsearch/update",
          "reason": {
            "reasonCode": 400,
            "reasonDescription": "Validation error:Incomplete/Incorrect Request : Missing or Extra fields"
          }
        }
      },
      "401ErrorResponse": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/401Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "POST/muni/v1/munibonds/savedsearch/update",
          "reason": {
            "reasonCode": 401,
            "reasonDescription": "Authentication Failure"
          }
        }
      },
      "403ErrorResponse": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/403Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "POST/muni/v1/munibonds/savedsearch/update",
          "reason": {
            "reasonCode": 403,
            "reasonDescription": "Forbidden"
          }
        }
      },
      "404ErrorResponse": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/404Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "POST/muni/v1/munibonds/savedsearch/update",
          "reason": {
            "reasonCode": 404,
            "reasonDescription": "Resource Not Found"
          }
        }
      },
      "405ErrorResponse": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/405Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/savedsearch/update",
          "reason": {
            "reasonCode": 405,
            "reasonDescription": "Method Not Allowed"
          }
        }
      },
      "406ErrorResponse": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/406Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "POST/muni/v1/munibonds/savedsearch/update",
          "reason": {
            "reasonCode": 406,
            "reasonDescription": "Not Acceptable"
          }
        }
      },
      "408ErrorResponse": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/408Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "POST/muni/v1/munibonds/savedsearch/update",
          "reason": {
            "reasonCode": 408,
            "reasonDescription": "HTTP Timeout Exception"
          }
        }
      },
      "415ErrorResponse": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/415Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "POST/muni/v1/munibonds/savedsearch/update",
          "reason": {
            "reasonCode": 415,
            "reasonDescription": "Unsupported Media Type"
          }
        }
      },
      "500ErrorResponse": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/500Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "POST/muni/v1/munibonds/savedsearch/update",
          "reason": {
            "reasonCode": 500,
            "reasonDescription": "Internal Server Error"
          }
        }
      },
      "503ErrorResponse": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/503Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "POST/muni/v1/munibonds/savedsearch/update",
          "reason": {
            "reasonCode": 503,
            "reasonDescription": "Service Unavailable"
          }
        }
      },
      "400Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "401Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "403Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "404Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "405Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "406Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "408Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "415Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "500Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "503Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      }
    }
  }
}