{
  "openapi": "3.0.1",
  "info": {
    "title": "Global Markets \u2013 Munibonds Bid Timings",
    "description": "Allows a user to retrieve the current BofA Municipal Desk Bid Timings.",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0",
    "x-additionalDocs": {
      "overview": {
        "fileName": ""
      }
    }
  },
  "tags": [
    {
      "name": "Muni Services"
    }
  ],
  "paths": {
    "/muni/v1/munibonds/bid/timings": {
      "get": {
        "tags": [
          "Muni Services"
        ],
        "summary": "APIs that allow BofA Securities customers of Municipal Banking and Markets to transact Municipal securities. This API provides the customer the ability to retrieve the current BofA Municipal Desk Bid Timings",
        "operationId": "",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "Identify the content of the payload as JSON. Use 'Content-Type: application/json'. This is the only content type supported as of now. Content-Types cannot be negotiated programmatically at this time. Future versions might provide that facility",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "A unique access token to be used for a single request (ex. \u201cBearer [value])",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "userId",
            "in": "header",
            "description": "User who is interacting with this service from a company. User should be on boarded on the BofA Securities Mercury\u2122 platform and obtain userId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "clientRequestId",
            "in": "header",
            "description": "A token provided by client to identify their request",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TimingsResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Timings400Error"
                }
              }
            }
          },
          "401": {
            "description": "Authentication Failure",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Timings401Error"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Timings403Error"
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Timings404Error"
                }
              }
            }
          },
          "405": {
            "description": "Method Not Allowed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Timings405Error"
                }
              }
            }
          },
          "406": {
            "description": "Not Acceptable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Timings406Error"
                }
              }
            }
          },
          "408": {
            "description": "HTTP Timeout Exception",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Timings408Error"
                }
              }
            }
          },
          "415": {
            "description": "Unsupported Media Type",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Timings415Error"
                }
              }
            }
          },
          "429": {
            "description": "API calls exceeded",
            "content": {}
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Timings500Error"
                }
              }
            }
          },
          "503": {
            "description": "Service unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Timings503Error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "400Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "401Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "403Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "404Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "405Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "406Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "408Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "415Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "500Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "503Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "TimingsResponse": {
        "type": "object",
        "properties": {
          "startTime": {
            "type": "string",
            "description": "The earliest time in the business day that a bid request can be submitted.<br><br>ISO 8601 date time format specifying date and time with HH, MM, SS and without time zone offsets. Time zone is always treated as US Eastern. See Wikipedia (<a href=\"https://en.wikipedia.org/wiki/ISO_8601\" target=\"blank\" rel=\"noopener noreferrer\">Link</a>) for ISO 8601. If caller uses Java, format guide is this (<a href=\"https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/DateFormatUtils.html#ISO_8601_EXTENDED_DATE_FORMAT\" target=\"_blank\" rel=\"noopener noreferrer\">Link</a>) for Apache Commons Lang date time format (ISO_8601_EXTENDED_DATE_FORMAT)\n",
            "example": "2020-02-10T12:00:00.000Z"
          },
          "bidByCutoffTime": {
            "type": "string",
            "description": "The latest time when a \u201cbid wanted\u201d can be submitted\n\nSee <strong>startTime</strong> for format and expectations\n\n",
            "example": "2020-02-10T22:00:00.000Z"
          },
          "firmTillCutOffTime": {
            "type": "string",
            "description": "The latest time the quoted price will be firm after which it becomes subject and cannot be executed electronically\n\nSee <strong>startTime</strong> for format and expectations\n\n",
            "example": "2020-02-10T22:00:00.000Z"
          },
          "shutdownTime": {
            "type": "string",
            "description": "The closing time of the bidding system. Might be the same as firmTillCutOffTime\n\nSee <strong>startTime</strong> for format and expectations\n\n",
            "example": "2020-02-10T22:00:00.000Z"
          }
        }
      },
      "Timings400Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/400Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "clientRequestId:123",
          "status": "Failure",
          "apiName": "muni/v1/munibonds/bid/timings",
          "reason": {
            "reasonCode": 400,
            "reasonDescription": "Validation error:Incomplete/Incorrect Request : Missing or Extra fields"
          }
        }
      },
      "Timings401Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/401Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/bid/timings",
          "reason": {
            "reasonCode": 401,
            "reasonDescription": "Authentication Failure"
          }
        }
      },
      "Timings403Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/403Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/bid/timings",
          "reason": {
            "reasonCode": 403,
            "reasonDescription": "Forbidden"
          }
        }
      },
      "Timings404Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/404Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/bid/timings",
          "reason": {
            "reasonCode": 404,
            "reasonDescription": "Resource Not Found"
          }
        }
      },
      "Timings405Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/405Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "POST/muni/v1/munibonds/bid/timings",
          "reason": {
            "reasonCode": 405,
            "reasonDescription": "Method Not Allowed"
          }
        }
      },
      "Timings406Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/406Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/bid/timings",
          "reason": {
            "reasonCode": 406,
            "reasonDescription": "Not Acceptable"
          }
        }
      },
      "Timings408Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/408Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/bid/timings",
          "reason": {
            "reasonCode": 408,
            "reasonDescription": "HTTP Timeout Exception"
          }
        }
      },
      "Timings415Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/415Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/bid/timings",
          "reason": {
            "reasonCode": 415,
            "reasonDescription": "Unsupported Media Type"
          }
        }
      },
      "Timings500Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/500Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/bid/timings",
          "reason": {
            "reasonCode": 500,
            "reasonDescription": "Internal Server Error"
          }
        }
      },
      "Timings503Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/503Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "99999990-9999-9999-9999-009099999999",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/bid/timings",
          "reason": {
            "reasonCode": 503,
            "reasonDescription": "Service Unavailable"
          }
        }
      }
    }
  }
}