{
  "openapi": "3.0.1",
  "info": {
    "title": "Global Markets \u2013 Munibonds Saved Search",
    "description": "Saved searches allow BofA to continuously monitor and send notifications when bonds match the customer\u2019s interest which is registered through saving a search.",
    "termsOfService": "",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0",
    "x-additionalDocs": {
      "overview": {
        "fileName": ""
      }
    }
  },
  "paths": {
    "/muni/v1/munibonds/savedsearch": {
      "get": {
        "tags": [
          "Muni Services"
        ],
        "summary": "APIs that allow BofA Securities customers of Municipal Banking and Markets to transact Municipal securities and retrieve their saved searches. Saved searches allow BofA to continuously monitor and send notifications when bonds match the customer\u2019s interest which is registered through saving a search",
        "operationId": "",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "Identify the content of the payload as JSON. Use 'Content-Type: application/json'. This is the only content type supported as of now. Content-Types cannot be negotiated programmatically at this time. Future versions might provide that facility",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "A unique access token to be used for a single request (ex. \u201cBearer [value])",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "userId",
            "in": "header",
            "description": "User who is interacting with this service from a company. User should be on boarded on the Bofa Securities Mercury\u2122 platform and obtain userId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "clientRequestId",
            "in": "header",
            "description": "A token provided by client to identify their request",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/savedSearchResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SavedSearch400Error"
                }
              }
            }
          },
          "401": {
            "description": "Authentication Failure",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SavedSearch401Error"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SavedSearch403Error"
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SavedSearch404Error"
                }
              }
            }
          },
          "405": {
            "description": "Method Not Allowed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SavedSearch405Error"
                }
              }
            }
          },
          "406": {
            "description": "Not Acceptable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SavedSearch406Error"
                }
              }
            }
          },
          "408": {
            "description": "HTTP Timeout Exception",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SavedSearch408Error"
                }
              }
            }
          },
          "415": {
            "description": "Unsupported Media Type",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SavedSearch415Error"
                }
              }
            }
          },
          "429": {
            "description": "API calls exceeded",
            "content": {}
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SavedSearch500Error"
                }
              }
            }
          },
          "503": {
            "description": "Service unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SavedSearch503Error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "400Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "401Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "403Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "404Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "405Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "406Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "408Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "415Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "500Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "503Reason": {
        "type": "object",
        "properties": {
          "reasonCode": {
            "type": "integer"
          },
          "reasonDescription": {
            "type": "string"
          }
        }
      },
      "savedSearchResponse": {
        "type": "object",
        "properties": {
          "savedSearches": {
            "type": "array",
            "description": "List of saved searches for user",
            "items": {
              "$ref": "#/components/schemas/SavedSearches"
            }
          }
        },
        "example": {
          "savedSearches": [
            {
              "criteria": [
                {
                  "field": "coupon",
                  "operand": "<=",
                  "value": "1"
                }
              ],
              "name": "1cpn",
              "notification": true
            },
            {
              "criteria": [
                {
                  "field": "coupon",
                  "operand": "<=",
                  "value": "2"
                }
              ],
              "name": "Coupon1",
              "notification": true
            }
          ]
        }
      },
      "SavedSearches": {
        "type": "object",
        "properties": {
          "criteria": {
            "type": "array",
            "description": "Criteria of saved search",
            "items": {
              "$ref": "#/components/schemas/CriteriaArray"
            }
          },
          "name": {
            "type": "string",
            "description": "Name of saved search",
            "example": "Coupon1"
          },
          "notification": {
            "type": "boolean",
            "description": "Set true if user needs any offer updates notification matching with saved search criteria. The Email address on file with BofA Securities Mercury\u2122 will receive an email when inventory matches this saved search",
            "example": true
          }
        }
      },
      "CriteriaArray": {
        "type": "object",
        "properties": {
          "field": {
            "type": "string",
            "description": "Field represent different offer criteria properties",
            "example": "coupon"
          },
          "operand": {
            "type": "string",
            "description": "Valid operand corresponding to field",
            "example": "<="
          },
          "value": {
            "type": "string",
            "description": "Value set for criteria field",
            "example": "2"
          }
        }
      },
      "SavedSearch400Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/400Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "clientRequestId:123",
          "status": "Failure",
          "apiName": "muni/v1/munibonds/savedsearch",
          "reason": {
            "reasonCode": 400,
            "reasonDescription": "Validation error:Incomplete/Incorrect Request : Missing or Extra fields"
          }
        }
      },
      "SavedSearch401Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/401Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "d7df57b0-37b8-11ea-8715-005056a7d6dc",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/savedsearch",
          "reason": {
            "reasonCode": 401,
            "reasonDescription": "Authentication Failure"
          }
        }
      },
      "SavedSearch403Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/403Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "4654681-37d3-11ea-92e7-005056a74762",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/savedsearch",
          "reason": {
            "reasonCode": 403,
            "reasonDescription": "Forbidden"
          }
        }
      },
      "SavedSearch404Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/404Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "29804110-37b9-11ea-99c7-005056a7d6dc",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/savedsearch",
          "reason": {
            "reasonCode": 404,
            "reasonDescription": "Resource Not Found"
          }
        }
      },
      "SavedSearch405Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/405Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "69524190-37b8-11ea-abc9-005056a7d6dc",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/savedsearch",
          "reason": {
            "reasonCode": 405,
            "reasonDescription": "Method Not Allowed"
          }
        }
      },
      "SavedSearch406Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/406Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "69524190-37b8-11ea-abc9-005056a7d6dc",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/savedsearch",
          "reason": {
            "reasonCode": 406,
            "reasonDescription": "Not Acceptable"
          }
        }
      },
      "SavedSearch408Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/408Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "69524190-37b8-11ea-abc9-005056a7d6dc",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/savedsearch",
          "reason": {
            "reasonCode": 408,
            "reasonDescription": "HTTP Timeout Exception"
          }
        }
      },
      "SavedSearch415Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/415Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "008030e0-37b9-11ea-abc9-005056a7d6dc",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/savedsearch",
          "reason": {
            "reasonCode": 415,
            "reasonDescription": "Unsupported Media Type"
          }
        }
      },
      "SavedSearch500Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/500Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "ae18f4d0-37b9-11ea-8ce3-005056a74762",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/savedsearch",
          "reason": {
            "reasonCode": 500,
            "reasonDescription": "Internal Server Error"
          }
        }
      },
      "SavedSearch503Error": {
        "type": "object",
        "properties": {
          "transactionIdentification": {
            "type": "string",
            "description": ""
          },
          "status": {
            "type": "string",
            "description": ""
          },
          "apiName": {
            "type": "string",
            "description": ""
          },
          "reason": {
            "$ref": "#/components/schemas/503Reason"
          }
        },
        "description": "",
        "example": {
          "transactionIdentification": "4654681-37d3-11ea-92e7-005056a74762",
          "status": "Failure",
          "apiName": "GET/muni/v1/munibonds/savedsearch",
          "reason": {
            "reasonCode": 503,
            "reasonDescription": "Service Unavailable"
          }
        }
      }
    }
  }
}